// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9It3PPWXAJPsV1Sla4MJ2q1g-AWZ3_A0',
    appId: '1:51965941877:web:4bfe773ca15800de80003c',
    messagingSenderId: '51965941877',
    projectId: 'flickmovies-fee9f',
    authDomain: 'flickmovies-fee9f.firebaseapp.com',
    storageBucket: 'flickmovies-fee9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Rq85AJ7wC_q0mhi-Qlxf1l4ZeU36dOA',
    appId: '1:51965941877:android:10546634601161c180003c',
    messagingSenderId: '51965941877',
    projectId: 'flickmovies-fee9f',
    storageBucket: 'flickmovies-fee9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQeYP8mPRIsXCPR2s7jrn7fIC2O4J05nw',
    appId: '1:51965941877:ios:13db83077cf738c180003c',
    messagingSenderId: '51965941877',
    projectId: 'flickmovies-fee9f',
    storageBucket: 'flickmovies-fee9f.firebasestorage.app',
    iosBundleId: 'com.example.flick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQeYP8mPRIsXCPR2s7jrn7fIC2O4J05nw',
    appId: '1:51965941877:ios:13db83077cf738c180003c',
    messagingSenderId: '51965941877',
    projectId: 'flickmovies-fee9f',
    storageBucket: 'flickmovies-fee9f.firebasestorage.app',
    iosBundleId: 'com.example.flick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9It3PPWXAJPsV1Sla4MJ2q1g-AWZ3_A0',
    appId: '1:51965941877:web:2f06abd9589706c280003c',
    messagingSenderId: '51965941877',
    projectId: 'flickmovies-fee9f',
    authDomain: 'flickmovies-fee9f.firebaseapp.com',
    storageBucket: 'flickmovies-fee9f.firebasestorage.app',
  );
}
